/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginEditorRouteImport } from './routes/login.editor'
import { Route as LoginAuthorRouteImport } from './routes/login.author'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEditorRoute = LoginEditorRouteImport.update({
  id: '/login/editor',
  path: '/login/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAuthorRoute = LoginAuthorRouteImport.update({
  id: '/login/author',
  path: '/login/author',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/author': typeof LoginAuthorRoute
  '/login/editor': typeof LoginEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login/author': typeof LoginAuthorRoute
  '/login/editor': typeof LoginEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login/author': typeof LoginAuthorRoute
  '/login/editor': typeof LoginEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login/author' | '/login/editor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login/author' | '/login/editor'
  id: '__root__' | '/' | '/login/author' | '/login/editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginAuthorRoute: typeof LoginAuthorRoute
  LoginEditorRoute: typeof LoginEditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/editor': {
      id: '/login/editor'
      path: '/login/editor'
      fullPath: '/login/editor'
      preLoaderRoute: typeof LoginEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/author': {
      id: '/login/author'
      path: '/login/author'
      fullPath: '/login/author'
      preLoaderRoute: typeof LoginAuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginAuthorRoute: LoginAuthorRoute,
  LoginEditorRoute: LoginEditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
