/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardReviewerRouteImport } from './routes/dashboard.reviewer'
import { Route as DashboardEditorRouteImport } from './routes/dashboard.editor'
import { Route as DashboardAuthorRouteImport } from './routes/dashboard.author'
import { Route as DashboardRoleRouteImport } from './routes/dashboard.$role'
import { Route as DashboardEditorSubmissionIdRouteImport } from './routes/dashboard.editor.submission.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReviewerRoute = DashboardReviewerRouteImport.update({
  id: '/dashboard/reviewer',
  path: '/dashboard/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEditorRoute = DashboardEditorRouteImport.update({
  id: '/dashboard/editor',
  path: '/dashboard/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuthorRoute = DashboardAuthorRouteImport.update({
  id: '/dashboard/author',
  path: '/dashboard/author',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoleRoute = DashboardRoleRouteImport.update({
  id: '/dashboard/$role',
  path: '/dashboard/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEditorSubmissionIdRoute =
  DashboardEditorSubmissionIdRouteImport.update({
    id: '/submission/$id',
    path: '/submission/$id',
    getParentRoute: () => DashboardEditorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/dashboard/author': typeof DashboardAuthorRoute
  '/dashboard/editor': typeof DashboardEditorRouteWithChildren
  '/dashboard/reviewer': typeof DashboardReviewerRoute
  '/dashboard/editor/submission/$id': typeof DashboardEditorSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/dashboard/author': typeof DashboardAuthorRoute
  '/dashboard/editor': typeof DashboardEditorRouteWithChildren
  '/dashboard/reviewer': typeof DashboardReviewerRoute
  '/dashboard/editor/submission/$id': typeof DashboardEditorSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/dashboard/author': typeof DashboardAuthorRoute
  '/dashboard/editor': typeof DashboardEditorRouteWithChildren
  '/dashboard/reviewer': typeof DashboardReviewerRoute
  '/dashboard/editor/submission/$id': typeof DashboardEditorSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/$role'
    | '/dashboard/author'
    | '/dashboard/editor'
    | '/dashboard/reviewer'
    | '/dashboard/editor/submission/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/$role'
    | '/dashboard/author'
    | '/dashboard/editor'
    | '/dashboard/reviewer'
    | '/dashboard/editor/submission/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dashboard/$role'
    | '/dashboard/author'
    | '/dashboard/editor'
    | '/dashboard/reviewer'
    | '/dashboard/editor/submission/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DashboardRoleRoute: typeof DashboardRoleRoute
  DashboardAuthorRoute: typeof DashboardAuthorRoute
  DashboardEditorRoute: typeof DashboardEditorRouteWithChildren
  DashboardReviewerRoute: typeof DashboardReviewerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reviewer': {
      id: '/dashboard/reviewer'
      path: '/dashboard/reviewer'
      fullPath: '/dashboard/reviewer'
      preLoaderRoute: typeof DashboardReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/editor': {
      id: '/dashboard/editor'
      path: '/dashboard/editor'
      fullPath: '/dashboard/editor'
      preLoaderRoute: typeof DashboardEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/author': {
      id: '/dashboard/author'
      path: '/dashboard/author'
      fullPath: '/dashboard/author'
      preLoaderRoute: typeof DashboardAuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$role': {
      id: '/dashboard/$role'
      path: '/dashboard/$role'
      fullPath: '/dashboard/$role'
      preLoaderRoute: typeof DashboardRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/editor/submission/$id': {
      id: '/dashboard/editor/submission/$id'
      path: '/submission/$id'
      fullPath: '/dashboard/editor/submission/$id'
      preLoaderRoute: typeof DashboardEditorSubmissionIdRouteImport
      parentRoute: typeof DashboardEditorRoute
    }
  }
}

interface DashboardEditorRouteChildren {
  DashboardEditorSubmissionIdRoute: typeof DashboardEditorSubmissionIdRoute
}

const DashboardEditorRouteChildren: DashboardEditorRouteChildren = {
  DashboardEditorSubmissionIdRoute: DashboardEditorSubmissionIdRoute,
}

const DashboardEditorRouteWithChildren = DashboardEditorRoute._addFileChildren(
  DashboardEditorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DashboardRoleRoute: DashboardRoleRoute,
  DashboardAuthorRoute: DashboardAuthorRoute,
  DashboardEditorRoute: DashboardEditorRouteWithChildren,
  DashboardReviewerRoute: DashboardReviewerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
